import { supabaseAdmin } from '../utils/db.js';
import { Resend } from 'resend';
import { verifyPaystackSignature } from '../utils/paystackSignature.js';
import { isDuplicateKeyError } from '../utils/supabaseErrors.js';

const PAYSTACK_SECRET_KEY = process.env.PAYSTACK_SECRET_KEY;
const RESEND_API_KEY = process.env.RESEND_API_KEY;
const resend = RESEND_API_KEY ? new Resend(RESEND_API_KEY) : null;

const TIER_AMOUNTS = {
  starter: 25000,
  growth: 55000,
  pro: 90000,
};

function clampMonths(months) {
  const m = Number(months);
  return [1, 3, 6, 12].includes(m) ? m : 1;
}

function toDateOnly(value) {
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return null;
  return d.toISOString().slice(0, 10);
}

function safeDivKoboToGhs(kobo) {
  const n = Number(kobo);
  if (!Number.isFinite(n)) return null;
  return n / 100;
}

async function computePeriodForPharmacy(pharmacy_id, months) {
  const now = new Date();
  const { data: pharmacy } = await supabaseAdmin
    .from('pharmacies')
    .select('current_period_end')
    .eq('id', pharmacy_id)
    .single();

  const currentEnd = pharmacy?.current_period_end
    ? new Date(pharmacy.current_period_end)
    : null;

  const baseStart = currentEnd && currentEnd > now ? currentEnd : now;
  const periodStart = toDateOnly(baseStart);
  const periodEndDate = new Date(baseStart);
  periodEndDate.setDate(periodEndDate.getDate() + (months * 30));
  const periodEnd = toDateOnly(periodEndDate);

  return { period_start: periodStart, period_end: periodEnd };
}

async function getPharmacyAdminEmail(pharmacy_id) {
  const { data } = await supabaseAdmin
    .from('profiles')
    .select('email, full_name')
    .eq('pharmacy_id', pharmacy_id)
    .eq('role', 'ADMIN')
    .maybeSingle();
  return { email: data?.email || null, full_name: data?.full_name || null };
}

async function getPharmacyName(pharmacy_id) {
  const { data } = await supabaseAdmin
    .from('pharmacies')
    .select('name')
    .eq('id', pharmacy_id)
    .single();
  return data?.name || null;
}

function extractPlanFromMeta(meta) {
  if (!meta) return null;
  return meta.tier || meta.plan || null;
}

function extractMonthsFromMeta(meta) {
  return clampMonths(meta?.months ?? 1);
}

function extractCustomerEmailFromPayload(payload) {
  return payload?.data?.customer?.email || payload?.customer?.email || null;
}

async function sendInvoiceEmail({
  to,
  pharmacy_name,
  plan,
  amount_ghs,
  months,
  period_start,
  period_end,
  reference,
}) {
  if (!resend || !to) return;
  const safeAmount = amount_ghs != null ? amount_ghs.toFixed(2) : '—';
  const safePlan = plan ? String(plan).toUpperCase() : '—';
  const safeMonths = months != null ? String(months) : '—';
  const safePeriodStart = period_start ? String(period_start) : '—';
  const safePeriodEnd = period_end ? String(period_end) : '—';
  const safeRef = reference ? String(reference) : '—';
  const safePharmacyName = pharmacy_name ? String(pharmacy_name) : 'Pharmacy Pilot';

  await resend.emails.send({
    from: 'Pharmacy Pilot <noreply@pharmacypilot.webdevv.io>',
    to,
    subject: 'Payment Receipt - Pharmacy Pilot',
    html: `
      <div style="font-family:sans-serif;max-width:640px;margin:0 auto;line-height:1.5;color:#0f172a;">
        <h2 style="margin:0 0 10px;">Payment Receipt</h2>
        <p style="margin: 0 0 16px;">Thanks for your payment to <strong>${safePharmacyName}</strong>.</p>
        <table style="width:100%;border-collapse:collapse;">
          <tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">Reference</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;"><strong>${safeRef}</strong></td></tr>
          <tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">Amount Paid (GHS)</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">${safeAmount}</td></tr>
          <tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">Plan</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">${safePlan}</td></tr>
          <tr><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">Period Covered</td><td style="padding:8px 0;border-bottom:1px solid #e2e8f0;">${safePeriodStart} to ${safePeriodEnd}</td></tr>
          <tr><td style="padding:8px 0;">Duration</td><td style="padding:8px 0;">${safeMonths} month(s)</td></tr>
        </table>
        <p style="margin-top:16px;color:#64748b;font-size:12px;">Generated by Pharmacy Pilot.</p>
      </div>
    `,
  });
}

export async function initializePayment(req, res) {
  try {
    const pharmacyId = req.userPharmacyId;
    const { months = 1 } = req.body;
    const validMonths = [1, 3, 6, 12].includes(months) ? months : 1;

    const { data: pharmacy, error } = await supabaseAdmin
      .from('pharmacies')
      .select('id, name, tier')
      .eq('id', pharmacyId)
      .single();

    if (error || !pharmacy) {
      return res.status(404).json({ error: 'Pharmacy not found' });
    }

    const { data: profile } = await supabaseAdmin
      .from('profiles')
      .select('email')
      .eq('id', req.user.id)
      .single();

    const amount = (TIER_AMOUNTS[pharmacy.tier] || TIER_AMOUNTS.starter) * validMonths;
    const callbackUrl = `${process.env.FRONTEND_URL}/payment-success`;

    const response = await fetch('https://api.paystack.co/transaction/initialize', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${PAYSTACK_SECRET_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email: profile.email,
        amount,
        currency: 'GHS',
        callback_url: callbackUrl,
        metadata: {
          pharmacy_id: pharmacyId,
          pharmacy_name: pharmacy.name,
          tier: pharmacy.tier,
          months: validMonths,
        },
      }),
    });

    const data = await response.json();
    if (!response.ok || !data.status) {
      console.error('[payments] Paystack init error', data);
      return res.status(502).json({ error: 'Failed to initialize payment' });
    }

    return res.json({
      authorization_url: data.data.authorization_url,
      reference: data.data.reference,
    });
  } catch (err) {
    console.error('[payments] initializePayment error', err);
    return res.status(500).json({ error: 'Failed to initialize payment' });
  }
}

export async function verifyPayment(req, res) {
  const { reference } = req.params;
  try {
    if (!PAYSTACK_SECRET_KEY) {
      return res.status(500).json({ error: 'Payment provider not configured' });
    }
    const response = await fetch(`https://api.paystack.co/transaction/verify/${reference}`, {
      headers: { Authorization: `Bearer ${PAYSTACK_SECRET_KEY}` },
    });
    const data = await response.json();

    if (!response.ok || !data.status || data.data.status !== 'success') {
      return res.status(400).json({ error: 'Payment not successful' });
    }

    const paystackRef = data?.data?.reference || reference;
    const meta = data.data.metadata || {};
    const { pharmacy_id } = meta || {};
    const validMonths = extractMonthsFromMeta(meta);
    const amount_ghs = safeDivKoboToGhs(data?.data?.amount);
    const plan = extractPlanFromMeta(meta);
    const customer_email = extractCustomerEmailFromPayload(data);
    const period = pharmacy_id ? await computePeriodForPharmacy(pharmacy_id, validMonths) : {};

    // Idempotency: only process a reference once
    const { error: insertErr } = await supabaseAdmin
      .from('payment_events')
      .insert({
        reference: paystackRef,
        event_source: 'verify',
        event_type: data?.data?.gateway_response || 'verify.success',
        pharmacy_id: pharmacy_id || null,
        months: validMonths,
        amount_ghs,
        plan,
        period_start: period.period_start || null,
        period_end: period.period_end || null,
        customer_email: customer_email || null,
        currency: 'GHS',
        payload: data,
      });

    // Duplicate reference: already applied
    if (insertErr && isDuplicateKeyError(insertErr)) {
      const { data: existing } = await supabaseAdmin
        .from('payment_events')
        .select('reference, amount_ghs, plan, months, period_start, period_end')
        .eq('reference', paystackRef)
        .single();
      return res.json({
        status: 'success',
        amount: existing?.amount_ghs ?? amount_ghs ?? safeDivKoboToGhs(data?.data?.amount),
        reference: paystackRef,
        already_processed: true,
        plan: existing?.plan ?? plan,
        months: existing?.months ?? validMonths,
        period_start: existing?.period_start ?? period.period_start ?? null,
        period_end: existing?.period_end ?? period.period_end ?? null,
      });
    }

    if (insertErr) {
      console.error('[payments] verifyPayment idempotency insert error', insertErr);
      return res.status(503).json({ error: 'Unable to confirm payment at this time' });
    }

    // Apply subscription update once
    if (pharmacy_id) {
      await supabaseAdmin
        .from('pharmacies')
        .update({
          subscription_status: 'active',
          current_period_end: period.period_end,
        })
        .eq('id', pharmacy_id);
    }

    // Send invoice email (best effort)
    if (resend && pharmacy_id && period?.period_end) {
      try {
        const admin = await getPharmacyAdminEmail(pharmacy_id);
        const pharmacy_name = await getPharmacyName(pharmacy_id);
        await sendInvoiceEmail({
          to: admin.email,
          pharmacy_name,
          plan,
          amount_ghs,
          months: validMonths,
          period_start: period.period_start,
          period_end: period.period_end,
          reference: paystackRef,
        });
      } catch (e) {
        console.error('[payments] invoice email failed', e);
      }
    }

    return res.json({
      status: 'success',
      amount: amount_ghs ?? safeDivKoboToGhs(data?.data?.amount),
      reference: paystackRef,
      plan,
      months: validMonths,
      period_start: period.period_start ?? null,
      period_end: period.period_end ?? null,
    });
  } catch (err) {
    console.error('[payments] verifyPayment error', err);
    return res.status(500).json({ error: 'Failed to verify payment' });
  }
}

export async function paystackWebhook(req, res) {
  const secret = PAYSTACK_SECRET_KEY;
  if (!secret) return res.status(500).send('Payment provider not configured');

  const signature = req.headers['x-paystack-signature'];
  const rawBody = req.body; // Buffer (set by express.raw in server.js)
  if (!rawBody || !Buffer.isBuffer(rawBody)) {
    return res.status(400).send('Invalid payload');
  }

  if (!verifyPaystackSignature(rawBody, secret, signature)) {
    return res.status(401).send('Invalid signature');
  }

  let event;
  try {
    event = JSON.parse(rawBody.toString('utf8'));
  } catch {
    return res.status(400).send('Invalid JSON');
  }

  if (event.event === 'charge.success') {
    const reference = event?.data?.reference || event?.data?.id || null;
    const meta = event.data?.metadata || {};
    const { pharmacy_id } = meta || {};
    const validMonths = extractMonthsFromMeta(meta);
    const amount_ghs = safeDivKoboToGhs(event?.data?.amount);
    const plan = extractPlanFromMeta(meta);
    const customer_email = extractCustomerEmailFromPayload(event);
    if (!pharmacy_id) return res.sendStatus(200);

    try {
      const period = await computePeriodForPharmacy(pharmacy_id, validMonths);

      // Idempotency: only process a reference once
      if (reference) {
        const { error: insertErr } = await supabaseAdmin
          .from('payment_events')
          .insert({
            reference: String(reference),
            event_source: 'webhook',
            event_type: event.event,
            pharmacy_id,
            months: validMonths,
            amount_ghs,
            plan,
            period_start: period?.period_start || null,
            period_end: period?.period_end || null,
            customer_email: customer_email || null,
            currency: 'GHS',
            payload: event,
          });

        if (insertErr && isDuplicateKeyError(insertErr)) {
          return res.sendStatus(200);
        }
        if (insertErr) {
          console.error('[payments] webhook idempotency insert error', insertErr);
          return res.sendStatus(200);
        }
      }

      // Extend subscription by the specified number of months
      await supabaseAdmin
        .from('pharmacies')
        .update({
          subscription_status: 'active',
          current_period_end: period.period_end,
        })
        .eq('id', pharmacy_id);

      console.log(`[payments] Subscription activated for pharmacy ${pharmacy_id} for ${validMonths} month(s)`);

      // Send invoice email (best effort)
      if (resend && pharmacy_id && period?.period_end) {
        try {
          const admin = await getPharmacyAdminEmail(pharmacy_id);
          const pharmacy_name = await getPharmacyName(pharmacy_id);
          await sendInvoiceEmail({
            to: admin.email,
            pharmacy_name,
            plan,
            amount_ghs,
            months: validMonths,
            period_start: period.period_start,
            period_end: period.period_end,
            reference: reference ? String(reference) : null,
          });
        } catch (e) {
          console.error('[payments] webhook invoice email failed', e);
        }
      }
    } catch (err) {
      console.error('[payments] Failed to update subscription', err);
    }
  }

  res.sendStatus(200);
}

export async function getPaymentHistory(req, res) {
  try {
    const pharmacyId = req.userPharmacyId;
    if (!pharmacyId) return res.json([]);

    const { data, error } = await supabaseAdmin
      .from('payment_events')
      .select('reference, amount_ghs, plan, months, period_start, period_end, processed_at')
      .eq('pharmacy_id', pharmacyId)
      .order('processed_at', { ascending: false })
      .limit(50);

    if (error) throw error;

    res.json(data || []);
  } catch (err) {
    res.status(500).json({ error: err.message || 'Failed to fetch payment history' });
  }
}
