export function exportReportDocument({ title, period, contentHtml, filename, pharmacy }) {
  const generatedAt = new Date().toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
  const safeName = (title || 'report').replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  const name = filename || `pharmacy-pilot-${safeName}-${Date.now()}.html`;

  const pharmacyName = pharmacy?.name || 'Pharmacy Pilot';
  const pharmacyMeta = [pharmacy?.address, pharmacy?.phone].filter(Boolean).join(' | ');

  const doc = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title || 'Report')} - ${escapeHtml(pharmacyName)}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      padding: 32px;
      max-width: 900px;
      margin-left: auto;
      margin-right: auto;
      color: #1e293b;
      line-height: 1.5;
    }
    .letterhead {
      margin-bottom: 24px;
      padding-bottom: 16px;
      border-bottom: 3px solid #2563eb;
    }
    .letterhead-name {
      font-size: 1.6rem;
      font-weight: 700;
      color: #0f172a;
      margin: 0 0 4px;
      letter-spacing: -0.01em;
    }
    .letterhead-meta {
      font-size: 0.85rem;
      color: #64748b;
      margin: 0;
    }
    .document-header {
      margin-bottom: 24px;
    }
    .document-header h1 {
      margin: 0 0 4px;
      font-size: 1.25rem;
      color: #0f172a;
      font-weight: 600;
    }
    .document-meta {
      font-size: 0.8rem;
      color: #94a3b8;
      margin: 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.9rem;
      margin-top: 8px;
    }
    th, td {
      padding: 10px 14px;
      text-align: left;
      border-bottom: 1px solid #e2e8f0;
    }
    th {
      background: #f8fafc;
      font-weight: 600;
      color: #475569;
      font-size: 0.8rem;
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    tfoot td {
      font-weight: 700;
      border-top: 2px solid #0f172a;
      background: #f8fafc;
    }
    .report-summary-inline p { margin: 0 0 16px; font-size: 0.95rem; color: #475569; }
    .empty-state { color: #94a3b8; font-size: 0.95rem; }
    .document-footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e2e8f0;
      font-size: 0.75rem;
      color: #94a3b8;
      display: flex;
      justify-content: space-between;
    }
    @media print {
      body { padding: 16px; }
    }
  </style>
</head>
<body>
  <div class="letterhead">
    <p class="letterhead-name">${escapeHtml(pharmacyName)}</p>
    ${pharmacyMeta ? `<p class="letterhead-meta">${escapeHtml(pharmacyMeta)}</p>` : ''}
  </div>
  <div class="document-header">
    <h1>${escapeHtml(title || 'Report')}</h1>
    <p class="document-meta">
      ${period ? `Period: ${escapeHtml(period)} &nbsp;·&nbsp; ` : ''}Generated: ${escapeHtml(generatedAt)}
    </p>
  </div>
  <div class="document-body">
    ${contentHtml || '<p class="empty-state">No content.</p>'}
  </div>
  <footer class="document-footer">
    <span>${escapeHtml(pharmacyName)}</span>
    <span>Generated by Pharmacy Pilot &nbsp;·&nbsp; For official use only.</span>
  </footer>
</body>
</html>`;

  const blob = new Blob([doc], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
