import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function exportReportDocument({ title, period, contentHtml, filename, pharmacy }) {
  const generatedAt = new Date().toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  });

  const pharmacyName = pharmacy?.name || 'Pharmacy Pilot';
  const pharmacyMeta = [pharmacy?.address, pharmacy?.phone].filter(Boolean).join(' | ');

  // Build a hidden render container
  const container = document.createElement('div');
  container.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 794px;
    background: white;
    padding: 48px;
    font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
    color: #1e293b;
    line-height: 1.5;
    box-sizing: border-box;
  `;

  container.innerHTML = `
    <div style="border-bottom: 3px solid #2563eb; padding-bottom: 14px; margin-bottom: 20px;">
      <p style="font-size: 22px; font-weight: 700; color: #0f172a; margin: 0 0 4px;">${escapeHtml(pharmacyName)}</p>
      ${pharmacyMeta ? `<p style="font-size: 13px; color: #64748b; margin: 0;">${escapeHtml(pharmacyMeta)}</p>` : ''}
    </div>
    <div style="margin-bottom: 20px;">
      <p style="font-size: 16px; font-weight: 600; margin: 0 0 4px; color: #0f172a;">${escapeHtml(title || 'Report')}</p>
      <p style="font-size: 12px; color: #94a3b8; margin: 0;">
        ${period ? `Period: ${escapeHtml(period)} &nbsp;·&nbsp; ` : ''}Generated: ${escapeHtml(generatedAt)}
      </p>
    </div>
    <div style="font-size: 13px;">
      ${contentHtml || '<p style="color:#94a3b8;">No content.</p>'}
    </div>
    <div style="margin-top: 40px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; display: flex; justify-content: space-between;">
      <span>${escapeHtml(pharmacyName)}</span>
      <span>Generated by Pharmacy Pilot &nbsp;·&nbsp; For official use only.</span>
    </div>
  `;

  // Fix table styles inside the container
  const style = document.createElement('style');
  style.textContent = `
    .pdf-container table { width: 100%; border-collapse: collapse; font-size: 13px; }
    .pdf-container th, .pdf-container td { padding: 9px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    .pdf-container th { background: #f8fafc; font-weight: 600; color: #475569; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
    .pdf-container tfoot td { font-weight: 700; border-top: 2px solid #0f172a; background: #f8fafc; }
    .pdf-container h3 { display: none; }
  `;
  container.classList.add('pdf-container');
  document.head.appendChild(style);
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'px',
      format: 'a4',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * pageWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // Add extra pages if content overflows
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    const safeName = (title || 'report').replace(/[^a-z0-9-]/gi, '-').toLowerCase();
    pdf.save(filename || `${safeName}-${Date.now()}.pdf`);
  } finally {
    document.body.removeChild(container);
    document.head.removeChild(style);
  }
}

function escapeHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
