/**
 * Export report content as a self-contained HTML document (suitable for saving, printing, or "Print to PDF").
 * @param {Object} opts
 * @param {string} opts.title - Report title (e.g. "Sales Summary")
 * @param {string} [opts.period] - Period label (e.g. "Month", "Custom: 2025-01-01 to 2025-01-31")
 * @param {string} opts.contentHtml - HTML string of the report body (e.g. from report-content element)
 * @param {string} [opts.filename] - Download filename (default derived from title)
 */
export function exportReportDocument({ title, period, contentHtml, filename }) {
  const generatedAt = new Date().toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
  const safeName = (title || 'report').replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  const name = filename || `pharmacy-pilot-${safeName}-${Date.now()}.html`;

  const doc = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title || 'Report')} - Pharmacy Pilot</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      padding: 24px;
      max-width: 900px;
      margin-left: auto;
      margin-right: auto;
      color: #1e293b;
      line-height: 1.5;
    }
    .document-header {
      border-bottom: 2px solid #2563eb;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .document-header h1 { margin: 0 0 4px; font-size: 1.5rem; color: #0f172a; }
    .document-meta { font-size: 0.875rem; color: #64748b; margin: 0; }
    .document-body { margin-top: 16px; }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.9rem;
    }
    th, td {
      padding: 10px 14px;
      text-align: left;
      border-bottom: 1px solid #e2e8f0;
    }
    th {
      background: #f8fafc;
      font-weight: 600;
      color: #475569;
    }
    .report-summary-inline p { margin: 0 0 16px; font-size: 0.95rem; color: #475569; }
    .empty-state { color: #94a3b8; font-size: 0.95rem; }
    .document-footer {
      margin-top: 32px;
      padding-top: 16px;
      border-top: 1px solid #e2e8f0;
      font-size: 0.8rem;
      color: #94a3b8;
    }
  </style>
</head>
<body>
  <header class="document-header">
    <h1>${escapeHtml(title || 'Report')}</h1>
    <p class="document-meta">
      ${period ? `Period: ${escapeHtml(period)} · ` : ''}Generated: ${escapeHtml(generatedAt)} · Pharmacy Pilot
    </p>
  </header>
  <div class="document-body">
    ${contentHtml || '<p class="empty-state">No content.</p>'}
  </div>
  <footer class="document-footer">
    This document was generated by Pharmacy Pilot. For official use only.
  </footer>
</body>
</html>`;

  const blob = new Blob([doc], { type: 'text/html;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = name;
  link.click();
  URL.revokeObjectURL(link.href);
}

function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
